/*
The five steps to explore data after cleaning and before the advance analysis 
include the 5 steps:
1-Database Exploration
2-Dimentions Exploration
3-Date Exploration
4-Measures Exploration
5-Magnitude Exploration
Include generating a report of the significant measures of this data
*/

PRINT '====================================';
PRINT 'EDA: 1-Database Exploration';
PRINT '====================================';
-- Explore all data in the database 
USE DataWarehouseAnalytics
SELECT * FROM INFORMATION_SCHEMA.TABLES

--explore all coulmns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

PRINT '====================================';
PRINT 'EDA: 2-Dimentions Exploration';
PRINT '====================================';
-- Explore all countries our customers come from 
SELECT DISTINCT country
FROM gold.dim_customers

-- Explore all categories "The major divisions"
SELECT DISTINCT category , subcategory , Product_name
FROM gold.dim_products
ORDER BY 1,2,3

PRINT '====================================';
PRINT 'EDA: 3-Date Exploration';
PRINT '====================================';
-- Explore the date of first and last order 
-- How many years of sales are avaliable
SELECT 
MIN(order_date) AS FirstOrderDate,
MAX(order_date) AS LastOrderDate,
DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS OrderRangeYears
FROM gold.fact_sales


-- Find the youngest and oldest customer
SELECT 
MIN(birthdate) OldestCustomer ,
MAX(birthdate) YoungestCustomer,
DATEDIFF(YEAR, MIN(birthdate),GETDATE()) AS OldestCustomerAge ,
DATEDIFF(YEAR, MAX(birthdate),GETDATE()) AS YoungestCustomerAge 
FROM gold.dim_customers

PRINT '====================================';
PRINT 'EDA: 4-Measures Exploration';
PRINT '====================================';
-- Find the total sales
SELECT 
SUM(sales_amount) AS TotalSales
FROM gold.fact_sales

-- Find how many items are sold 
SELECT 
SUM(quantity) AS TotalQuantity
FROM gold.fact_sales

-- Find the average selling price 
SELECT 
AVG(price) AS AveragePrice
FROM gold.fact_sales

-- Find the total number of orders 
SELECT 
COUNT(DISTINCT order_number) AS TotalOrders
FROM gold.fact_sales

-- Find the total number of products
SELECT 
COUNT(DISTINCT product_key) AS TotalProduct
FROM gold.dim_products

-- Find the total number of customers 
SELECT 
COUNT(Customer_key) AS TotalCustomer
FROM gold.dim_customers

-- Find the total number of customers that have placed an order 
SELECT 
COUNT(DISTINCT Customer_key) AS TotalCustomersPlaceOrder
FROM gold.fact_sales

-- Generate a report that shows all key metrics of the business
SELECT 'TotalSales' AS MeasureName , SUM(sales_amount) AS MeasureValue FROM gold.fact_sales
UNION ALL 
SELECT 'TotalQuantity' AS MeasureName , SUM(quantity) AS MeasureValue FROM gold.fact_sales
UNION ALL
SELECT 'AveragePrice' AS MeasureName , AVG(price) AS MeasureValue FROM gold.fact_sales
UNION ALL 
SELECT 'TotalOrders' AS MeasureName , COUNT(DISTINCT order_number) AS MeasureValue FROM gold.fact_sales
UNION ALL 
SELECT 'TotalProduct' AS MeasureName , COUNT(DISTINCT product_key) AS MeasureValue  FROM gold.dim_products
UNION ALL 
SELECT 'TotalCustomer' AS MeasureName, COUNT(Customer_key) AS MeasureValue FROM gold.dim_customers
UNION ALL 
SELECT 'TotalCustomersPlaceOrder' AS MeasureName, COUNT(Customer_key) AS MeasureValue FROM gold.fact_sales


---============
PRINT '====================================';
PRINT 'EDA: 5-Magnitude Exploration';
PRINT '====================================';
-- Find the total customers by countries
SELECT country,
COUNT (customer_key) AS Total_Customers
FROM gold.dim_customers
GROUP BY country 
ORDER BY Total_Customers DESC

-- Find the total customers by gender 
SELECT gender,
COUNT (customer_key) AS Total_Customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY Total_Customers DESC

-- Find total products by category
SELECT category,
COUNT (product_key) AS Total_Products
FROM gold.dim_products
GROUP BY category 
ORDER BY Total_Products DESC

-- What is the avevrage costs in each category?
SELECT 
category,
AVG (cost) AS Average_Cost
FROM gold.dim_products
GROUP BY category
ORDER BY Average_Cost DESC

-- What is the total revenue generatd for each category?
SELECT 
p.category,
SUM (s.sales_amount) AS Total_Revenue
FROM gold.fact_sales s
LEFT JOIN  gold.dim_products P
ON s.product_key = p.product_key
GROUP BY category
ORDER BY Total_Revenue DESC

-- Find total revenue is generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM (s.sales_amount) AS Total_Revenue
FROM gold.fact_sales s
LEFT JOIN  gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_Revenue DESC

-- What is the distribution of sold items across countries?
SELECT 
c.country,
SUM (s.quantity) AS Total_Sold_Items
FROM gold.fact_sales s
LEFT JOIN  gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY Total_Sold_Items DESC

PRINT '====================================';
PRINT 'EDA: 6-Ranking Exploration';
PRINT '====================================';
-- Which 5 products generate teh higest revenu ?
SELECT TOP 5
p.product_name,
SUM (s.sales_amount) AS Total_Revenue
FROM gold.fact_sales s
LEFT JOIN  gold.dim_products P
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY Total_Revenue DESC
-- Same task using window function 
SELECT * 
FROM (
	SELECT 
	p.product_name,
	SUM (s.sales_amount) AS Total_Revenue,
	ROW_NUMBER() OVER (ORDER BY SUM (s.sales_amount)) AS Rank_Products
	FROM gold.fact_sales s
	LEFT JOIN  gold.dim_products P
	ON s.product_key = p.product_key
	GROUP BY p.product_name
	) t
WHERE Rank_Products <=5

-- What are the  5 worset-performing products in terms of sales ?
SELECT TOP 5
p.product_name,
SUM (s.sales_amount) AS Total_Revenue
FROM gold.fact_sales s
LEFT JOIN  gold.dim_products P
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY Total_Revenue ASC

-- Find the top 10 customers who have generated the highest revenue 

SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM (s.sales_amount) AS Total_Revenue
FROM gold.fact_sales s
LEFT JOIN  gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_Revenue DESC

-- Find the 3 customers with the fewest orders placed 

SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT s.order_number) AS Total_Orders
FROM gold.fact_sales s
LEFT JOIN  gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_Orders ASC
